version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: controle-estoque-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: eduarda
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: controle_estoque
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eduarda -d controle_estoque"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação NestJS
  app:
    build: .
    container_name: controle-estoque-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://eduarda:123456@postgres:5432/controle_estoque?schema=public
    ports:
      - "3000:3000"
    networks:
      - app-network
    command: sh -c "npx prisma db push --accept-data-loss && node dist/main"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge